# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48f61614204f4ad83249e80f42411b6a10e4118938dc2f5609127c7e0f982b114f650dbb76f8cdc45376a8499a3ad4d895a5c79071df9d434c45d596c89f0763

test:
  secret_key_base: 90630a15203b70b638fe57f7cd3059d91ddbecc0718c4bb8a26da4b664f53922023611fb65b708da4d8545d6ffd4a7518e7ccdab6bbc3d0686132cd27b7eff32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
